# Generated by Django 4.1.11 on 2023-10-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_ids', models.ManyToManyField(to='Payment.new_payment')),
            ],
        ),
    ]
