# Generated by Django 4.1.11 on 2023-10-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_new_payment_recipient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='new_payment',
            name='recipient_id',
            field=models.CharField(max_length=255),
        ),
    ]
